# Generated by Django 4.1 on 2022-11-26 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reconinfra_Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='Recon/Media-Center')),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('plot_map', models.FileField(blank=True, null=True, upload_to='Recon/PlotAvailability')),
                ('plot_types', models.CharField(choices=[('Residential', 'Residential'), ('Industrial', 'Industrial'), ('Commercial', 'Commercial')], default='Commercial', max_length=100, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='Recon/User/Reward')),
                ('is_lock', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertiesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='Recon/Properties-img')),
                ('properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reconinfra_Admin_Panel.properties')),
            ],
        ),
        migrations.CreateModel(
            name='PlotNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_status', models.CharField(choices=[('Freeze', 'Freeze'), ('Available', 'Available'), ('Booked', 'Booked'), ('Registerd', 'Registerd')], default='Available', max_length=100, null=True)),
                ('plot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('properties', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Reconinfra_Admin_Panel.properties')),
            ],
        ),
        migrations.CreateModel(
            name='PlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('customer_father_name', models.CharField(max_length=100, null=True)),
                ('customer_phone', models.CharField(max_length=100, null=True)),
                ('plot_number', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=50, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Reconinfra_Accounts.city')),
                ('plot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Reconinfra_Admin_Panel.properties')),
                ('plot_availability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Reconinfra_Admin_Panel.plotnumber')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pay_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(choices=[('Full Payment', 'Full Payment'), ('EMI', 'EMI')], default='EMI', max_length=100, null=True)),
                ('emi_period', models.CharField(choices=[('12', '12 Months'), ('18', '18 Months')], default='12 Months', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Reconinfra_Admin_Panel.plotbooking')),
            ],
        ),
    ]
