# Generated by Django 4.2.4 on 2023-09-06 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='Recon/Media-Center')),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('plot_map', models.FileField(blank=True, null=True, upload_to='Recon/PlotAvailability')),
                ('plot_types', models.CharField(choices=[('Residential', 'Residential'), ('Industrial', 'Industrial'), ('Commercial', 'Commercial')], default='Commercial', max_length=100, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_balance', models.IntegerField(default=0, null=True)),
                ('total_business', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('associate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfer_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='Recon/User/Reward')),
                ('is_lock', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertiesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='Recon/Properties-img')),
                ('properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reconinfra_Admin_Panel.properties')),
            ],
        ),
        migrations.CreateModel(
            name='PlotNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_status', models.CharField(choices=[('Freeze', 'Freeze'), ('Available', 'Available'), ('Booked', 'Booked'), ('Registerd', 'Registerd')], default='Available', max_length=100, null=True)),
                ('plot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('properties', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Reconinfra_Admin_Panel.properties')),
            ],
        ),
        migrations.CreateModel(
            name='PlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associate_id', models.CharField(max_length=10, null=True)),
                ('plot_number', models.CharField(max_length=10, null=True)),
                ('plot_size', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('sun_of', models.CharField(max_length=100, null=True)),
                ('dob', models.CharField(blank=True, max_length=100, null=True)),
                ('current_address', models.CharField(blank=True, max_length=100, null=True)),
                ('current_pin_code', models.CharField(max_length=100, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_pin_code', models.CharField(max_length=100, null=True)),
                ('customer_phone', models.CharField(max_length=100, null=True)),
                ('customer_mobile_phone', models.CharField(max_length=100, null=True)),
                ('customer_email', models.CharField(max_length=100, null=True)),
                ('customer_username', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_password', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_aadhar', models.CharField(max_length=100, null=True)),
                ('customer_pan', models.CharField(max_length=100, null=True)),
                ('booking_method', models.CharField(choices=[('Full Payment', 'Full Payment'), ('EMI', 'EMI')], default='EMI', max_length=100, null=True)),
                ('emi_period', models.CharField(blank=True, choices=[('12', '12 Months'), ('24', '24 Months'), ('36', '36 Months'), ('48', '48 Months'), ('60', '60 Months')], default='12 Months', max_length=100, null=True)),
                ('payment_method', models.CharField(choices=[('Cheque', 'Cheque'), ('DD', 'DD'), ('Cash', 'Cash')], default='Cash', max_length=100, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('down_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('remaining_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('plot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Reconinfra_Admin_Panel.properties')),
            ],
        ),
    ]
