# Generated by Django 4.2.4 on 2023-08-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='total_business',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
