# Generated by Django 4.2.4 on 2023-09-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotbooking',
            name='booking_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=100, null=True),
        ),
    ]
