# Generated by Django 4.1 on 2022-11-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotbooking',
            name='booking_id',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
