# Generated by Django 4.2.4 on 2023-09-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0002_plotbooking_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotbooking',
            name='booking_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plotbooking',
            name='plot_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
