# Generated by Django 4.1 on 2022-12-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0003_alter_paymenthistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='remaining_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
