# Generated by Django 4.2.4 on 2023-09-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0003_plotbooking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotbooking',
            name='plot_number',
            field=models.CharField(error_messages={'unique': 'This plot number has been already booked!'}, max_length=10, null=True, unique=True),
        ),
    ]
