# Generated by Django 4.1 on 2022-12-06 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0004_paymenthistory_remaining_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'ordering': ['-created_at']},
        ),
    ]
