# Generated by Django 4.2.4 on 2023-09-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0005_alter_plotbooking_remaining_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotbooking',
            name='emi_period',
            field=models.CharField(blank=True, choices=[('12 Months', '12'), ('24 Months', '24'), ('36 Months', '36'), ('48 Months', '48'), ('60 Months', '60')], default='12', max_length=100, null=True),
        ),
    ]
