# Generated by Django 4.2.4 on 2023-09-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0007_alter_plotbooking_emi_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotbooking',
            name='emi_period',
            field=models.CharField(blank=True, choices=[('12', '12 Months'), ('24', '24 Months'), ('36', '36 Months'), ('48', '48 Months'), ('60', '60 Months')], default=0, max_length=100, null=True),
        ),
    ]
