# Generated by Django 4.2.4 on 2023-09-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0010_alter_plotbooking_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotbooking',
            name='payment_method',
            field=models.CharField(choices=[('Cheque', 'Cheque'), ('DD', 'DD'), ('Cash', 'Cash'), ('NEFT/IMPS/RTGS', 'NEFT/IMPS/RTGS')], default='Cash', max_length=100, null=True),
        ),
    ]
