# Generated by Django 4.2.4 on 2023-09-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0011_alter_plotbooking_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotbooking',
            name='plot_rate_square_fit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
