# Generated by Django 4.2.4 on 2023-09-19 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0012_plotbooking_plot_rate_square_fit'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMIHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emi_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emi_date', models.CharField(blank=True, max_length=100, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('booking_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Reconinfra_Admin_Panel.plotbooking')),
            ],
        ),
    ]
