# Generated by Django 4.2.4 on 2023-09-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0013_emihistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='Recon/Properties-img'),
        ),
        migrations.AddField(
            model_name='properties',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='Recon/Properties-img'),
        ),
        migrations.AddField(
            model_name='properties',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='Recon/Properties-img'),
        ),
        migrations.AddField(
            model_name='properties',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='Recon/Properties-img'),
        ),
        migrations.AlterField(
            model_name='plotbooking',
            name='customer_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plotbooking',
            name='customer_pan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
