# Generated by Django 4.2.4 on 2023-09-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0014_properties_image_1_properties_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emihistory',
            name='booking_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
