# Generated by Django 4.2.4 on 2023-09-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0015_alter_emihistory_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='date_time',
        ),
        migrations.AddField(
            model_name='reward',
            name='business',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='time_limit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
