# Generated by Django 4.2.4 on 2023-09-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0016_remove_reward_date_time_reward_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='business_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
