# Generated by Django 4.2.4 on 2023-09-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0017_wallet_business_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
