# Generated by Django 4.2.4 on 2023-10-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0018_alter_wallet_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='emihistory',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emihistory',
            name='payment_method',
            field=models.CharField(choices=[('Cheque', 'Cheque'), ('DD', 'DD'), ('Cash', 'Cash'), ('NEFT/IMPS/RTGS', 'NEFT/IMPS/RTGS')], default='Cash', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plotbooking',
            name='booking_status',
            field=models.CharField(choices=[('Saved', 'Saved'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Saved', max_length=100, null=True),
        ),
    ]
