# Generated by Django 4.2.4 on 2023-10-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0019_emihistory_cheque_number_emihistory_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emihistory',
            old_name='emi_date',
            new_name='payment_date',
        ),
    ]
