# Generated by Django 4.2.4 on 2023-10-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0020_rename_emi_date_emihistory_payment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emihistory',
            old_name='emi_amount',
            new_name='amount',
        ),
    ]
