# Generated by Django 4.2.4 on 2023-10-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0021_rename_emi_amount_emihistory_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emihistory',
            old_name='cheque_number',
            new_name='number',
        ),
    ]
