# Generated by Django 4.2.4 on 2023-10-24 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0025_alter_emihistory_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotnumber',
            name='properties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Reconinfra_Admin_Panel.properties'),
        ),
        migrations.CreateModel(
            name='PlotAvailabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_status', models.CharField(choices=[('Hold', 'Hold'), ('Available', 'Available'), ('Booked', 'Booked'), ('Registerd', 'Registerd'), ('Pending', 'Pending')], default='Available', max_length=100, null=True)),
                ('plot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('properties', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Reconinfra_Admin_Panel.properties')),
            ],
        ),
    ]
