# Generated by Django 4.2.4 on 2023-10-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0028_alter_plotavailabilities_plot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotavailabilities',
            name='plot_number',
            field=models.CharField(blank=True, error_messages={'unique': 'Plot Number Already Exist'}, max_length=100, null=True, unique=True),
        ),
    ]
