# Generated by Django 4.2.4 on 2023-10-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0029_alter_plotavailabilities_plot_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotavailabilities',
            name='plot_dimensions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
