# Generated by Django 4.2.4 on 2023-11-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0030_plotavailabilities_plot_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='plot_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
