# Generated by Django 4.2.4 on 2023-11-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0032_claimedreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='status',
            field=models.CharField(blank=True, choices=[('Lock', 'Lock'), ('Unlock', 'Unlock'), ('Claimed', 'Claimed')], default='Lock', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='claimedreward',
            name='status',
            field=models.CharField(blank=True, choices=[('Requested', 'Requested'), ('Transferd', 'Transferd')], max_length=100, null=True),
        ),
    ]
