# Generated by Django 4.2.4 on 2023-11-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0033_reward_status_alter_claimedreward_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotbooking',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
