# Generated by Django 4.2.4 on 2023-11-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0034_plotbooking_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotbooking',
            name='emi_date',
            field=models.CharField(blank=True, choices=[('05', '05'), ('25', '25')], max_length=50, null=True),
        ),
    ]
