# Generated by Django 4.2.4 on 2023-11-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0035_plotbooking_emi_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='emihistory',
            name='emi_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
