# Generated by Django 4.1 on 2022-09-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Home', '0002_alter_contactus_email_alter_contactus_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='email',
        ),
        migrations.AddField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
