# Generated by Django 4.1 on 2022-11-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Accounts', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_group_admin',
            field=models.BooleanField(default=False),
        ),
    ]
