# Generated by Django 4.1 on 2023-01-14 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Accounts', '0004_customuser_forget_password_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='is_group_admin',
            new_name='is_group_owner',
        ),
    ]
