# Generated by Django 4.1 on 2023-01-15 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Accounts', '0005_rename_is_group_admin_group_is_group_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='agent',
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='agent',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
