# Generated by Django 4.2.4 on 2023-09-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Accounts', '0005_alter_customuser_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
