# Generated by Django 4.2.4 on 2023-08-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Accounts', '0008_remove_customuser_group_remove_group_is_group_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_wallet_active',
            field=models.BooleanField(default=False),
        ),
    ]
