# Generated by Django 4.2.4 on 2023-08-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Accounts', '0009_customuser_is_wallet_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='business_level',
            field=models.CharField(blank=True, choices=[('Level1', 'Level1'), ('Level2', 'Level2'), ('Level3', 'Level3'), ('Level4', 'Level4'), ('Level5', 'Level5'), ('Level6', 'Level6'), ('Level7', 'Level7'), ('Level8', 'Level8'), ('Level9', 'Level9'), ('Level10', 'Level10')], default='Level1', max_length=20, null=True),
        ),
    ]
