# Generated by Django 4.1.4 on 2023-08-21 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reconinfra_Admin_Panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotbooking',
            name='booking_method',
            field=models.CharField(choices=[('Full Payment', 'Full Payment'), ('EMI', 'EMI')], default='EMI', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plotbooking',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='plotbooking',
            name='payment_method',
            field=models.CharField(choices=[('Cheque', 'Cheque'), ('DD', 'DD'), ('Cash', 'Cash')], default='Cash', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfer_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
