# Generated by Django 4.1.4 on 2023-08-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0002_plotbooking_booking_method_plotbooking_cheque_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plotbooking',
            old_name='pin',
            new_name='current_address',
        ),
        migrations.RenameField(
            model_name='plotbooking',
            old_name='customer_father_name',
            new_name='current_pin_code',
        ),
        migrations.RemoveField(
            model_name='plotbooking',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='plotbooking',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='plotbooking',
            name='location',
        ),
        migrations.RemoveField(
            model_name='plotbooking',
            name='plot_availability',
        ),
        migrations.RemoveField(
            model_name='plotbooking',
            name='status',
        ),
        migrations.AddField(
            model_name='plotbooking',
            name='associate_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='plotbooking',
            name='customer_aadhar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plotbooking',
            name='customer_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plotbooking',
            name='customer_mobile_phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plotbooking',
            name='customer_pan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plotbooking',
            name='dob',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plotbooking',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plotbooking',
            name='permanent_pin_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plotbooking',
            name='plot_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plotbooking',
            name='sun_of',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plotbooking',
            name='down_payment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plotbooking',
            name='emi_period',
            field=models.CharField(choices=[('12', '12 Months'), ('24', '24 Months'), ('36', '36 Months'), ('48', '48 Months'), ('60', '60 Months')], default='12 Months', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plotbooking',
            name='plot_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='plotbooking',
            name='total_amount',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
