# Generated by Django 4.1.4 on 2023-09-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0003_rename_pin_plotbooking_current_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='agent',
            new_name='associate',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
        migrations.AddField(
            model_name='plotbooking',
            name='booking_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plotbooking',
            name='booking_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plotbooking',
            name='customer_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plotbooking',
            name='customer_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plotbooking',
            name='remaining_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_business',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_balance',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plotbooking',
            name='down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='plotbooking',
            name='emi_period',
            field=models.CharField(blank=True, choices=[('12', '12 Months'), ('24', '24 Months'), ('36', '36 Months'), ('48', '48 Months'), ('60', '60 Months')], default='12 Months', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plotbooking',
            name='plot_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='plotbooking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
