# Generated by Django 4.1.4 on 2023-09-17 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0005_alter_plotbooking_emi_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotbooking',
            name='booking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plotbooking',
            name='plot_rate_square_fit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plotbooking',
            name='payment_method',
            field=models.CharField(choices=[('Cheque', 'Cheque'), ('DD', 'DD'), ('Cash', 'Cash'), ('NEFT/IMPS/RTGS', 'NEFT/IMPS/RTGS')], default='Cash', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='EMIHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emi_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emi_date', models.CharField(blank=True, max_length=100, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('booking_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Reconinfra_Admin_Panel.plotbooking')),
            ],
        ),
    ]
