# Generated by Django 4.1.4 on 2023-10-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0007_properties_image_1_properties_image_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='date_time',
        ),
        migrations.AddField(
            model_name='reward',
            name='business',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='time_limit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='business_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
