# Generated by Django 4.1.4 on 2023-10-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0008_remove_reward_date_time_reward_business_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emihistory',
            old_name='emi_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='emihistory',
            old_name='emi_date',
            new_name='number',
        ),
        migrations.AddField(
            model_name='emihistory',
            name='booking_status',
            field=models.CharField(blank=True, choices=[('Saved', 'Saved'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Saved', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emihistory',
            name='payment_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emihistory',
            name='payment_method',
            field=models.CharField(choices=[('Cheque', 'Cheque'), ('DD', 'DD'), ('Cash', 'Cash'), ('NEFT/IMPS/RTGS', 'NEFT/IMPS/RTGS')], default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plotbooking',
            name='booking_status',
            field=models.CharField(choices=[('Saved', 'Saved'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Saved', max_length=100, null=True),
        ),
    ]
