# Generated by Django 4.1.4 on 2023-10-25 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reconinfra_Admin_Panel', '0009_rename_emi_amount_emihistory_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotnumber',
            name='properties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Reconinfra_Admin_Panel.properties'),
        ),
        migrations.CreateModel(
            name='PlotAvailabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_status', models.CharField(choices=[('hold', 'Hold'), ('available', 'Available'), ('booked', 'Booked'), ('registered', 'Registered'), ('pending', 'Pending')], default='available', max_length=100, null=True)),
                ('plot_dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('plot_number', models.CharField(blank=True, error_messages={'unique': 'Plot Number Already Exist'}, max_length=100, null=True, unique=True)),
                ('properties', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Reconinfra_Admin_Panel.properties')),
            ],
        ),
    ]
